[build]
  command = "npm run build"
  publish = "frontend/build"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200